<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
  </ItemGroup>


  <ItemGroup>
    <None Remove="SeedData\" />
    <None Remove="helper\" />
    <None Remove="Newtonsoft.Json" />
    <None Remove="Microsoft.EntityFrameworkCore" />
    <None Remove="EntityFramework" />
    <None Remove="SeedData\Meter_Reading.csv" />
    <None Remove="Models\RequestObjects\" />
    <None Remove="Models\ReturnObjects\" />
    <None Remove="Models\DBObjects\" />
    <None Remove="Serilog.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="SeedData\" />
    <Folder Include="helpers\" />
    <Folder Include="Models\RequestObjects\" />
    <Folder Include="Models\ReturnObjects\" />
    <Folder Include="Models\DBObjects\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="SeedData\Test_Accounts.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SeedData\Test_Accounts.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SeedData\Meter_Reading.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
</Project>
